name = "qter-api"
main = "api/worker/src/index.ts"
compatibility_date = "2024-09-10"
# compatibility_flags = ["nodejs_compat"]  # 如需 Node 相容性再開

# 本地開發
[dev]
port = 8787
local_protocol = "http"

# 可先用 /api/* 作為 Workers 路徑，日後再綁定自訂網域路由
# routes = ["https://your-domain.com/api/*"]

# D1 資料庫（執行 wrangler d1 create qter-db 取得 database_id）
[[d1_databases]]
binding = "DB"                 # Workers 代碼內的變數名 env.DB
database_name = "qter-db"
database_id = "70de02b7-119e-407a-857b-cacea2a940eb"  # ✅ 已設定
migrations_dir = "api/worker/migrations"

# KV 命名空間（選用，先註解掉以便部署）
# [[kv_namespaces]]
# binding = "RATE_LIMIT"         # Workers 代碼內的變數名 env.RATE_LIMIT
# id = "YOUR_KV_NAMESPACE_ID"  # 需要在 Dashboard 建立後填入

# 觀測
[observability]
enabled = true

# 預設變數（部署前請改為實際值或以 wrangler secret 設定）
[vars]
ENV = "dev"
RATE_LIMIT_RPM = "60"
HASH_LENGTH = "12"
JWT_SECRET = "REPLACE_WITH_RANDOM_SECRET"
TURNSTILE_SITE_KEY = "REPLACE_WITH_TURNSTILE_SITE_KEY"

# 機密請用 secret 設定（wrangler secret put TURNSTILE_SECRET_KEY）